// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADeAO7Yc9u5RhMM-GvekY9QCyKVHAXfxc',
    appId: '1:681058687134:web:1479b3911a7811d7c7438f',
    messagingSenderId: '681058687134',
    projectId: 'cannasoltech',
    authDomain: 'cannasoltech.firebaseapp.com',
    databaseURL: 'https://cannasoltech-default-rtdb.firebaseio.com',
    storageBucket: 'cannasoltech.firebasestorage.app',
    measurementId: 'G-6TMV8L9NX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoZEfLt5vObq2UQO1RM7x_yENvobWzRo',
    appId: '1:681058687134:android:226599577d4fa831c7438f',
    messagingSenderId: '681058687134',
    projectId: 'cannasoltech',
    databaseURL: 'https://cannasoltech-default-rtdb.firebaseio.com',
    storageBucket: 'cannasoltech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpCrx581Twp6VGsseMtQbYCurCJt8Lnk',
    appId: '1:681058687134:ios:9cf9446c3da3577dc7438f',
    messagingSenderId: '681058687134',
    projectId: 'cannasoltech',
    databaseURL: 'https://cannasoltech-default-rtdb.firebaseio.com',
    storageBucket: 'cannasoltech.firebasestorage.app',
    androidClientId: '681058687134-6f8atkd860tsnukq32m2pk3qm3nija23.apps.googleusercontent.com',
    iosClientId: '681058687134-s5l7lnk515adhmjkt9amndke3rnb2ern.apps.googleusercontent.com',
    iosBundleId: 'com.cannasol-technologies.automation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpCrx581Twp6VGsseMtQbYCurCJt8Lnk',
    appId: '1:681058687134:ios:9cf9446c3da3577dc7438f',
    messagingSenderId: '681058687134',
    projectId: 'cannasoltech',
    databaseURL: 'https://cannasoltech-default-rtdb.firebaseio.com',
    storageBucket: 'cannasoltech.firebasestorage.app',
    androidClientId: '681058687134-6f8atkd860tsnukq32m2pk3qm3nija23.apps.googleusercontent.com',
    iosClientId: '681058687134-s5l7lnk515adhmjkt9amndke3rnb2ern.apps.googleusercontent.com',
    iosBundleId: 'com.cannasol-technologies.automation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADeAO7Yc9u5RhMM-GvekY9QCyKVHAXfxc',
    appId: '1:681058687134:web:1479b3911a7811d7c7438f',
    messagingSenderId: '681058687134',
    projectId: 'cannasoltech',
    authDomain: 'cannasoltech.firebaseapp.com',
    databaseURL: 'https://cannasoltech-default-rtdb.firebaseio.com',
    storageBucket: 'cannasoltech.firebasestorage.app',
    measurementId: 'G-6TMV8L9NX6',
  );

}