name: Flutter CI

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      working-directory: ./cannasoltech_automation
      run: flutter pub get
      
    - name: Verify Flutter setup
      working-directory: ./cannasoltech_automation
      run: flutter doctor -v
      
    - name: Analyze code
      working-directory: ./cannasoltech_automation
      run: flutter analyze --no-fatal-infos
      
    - name: Run tests with detailed output
      working-directory: ./cannasoltech_automation
      run: |
        echo "Running Flutter tests..."
        flutter test --reporter=expanded --coverage || exit_code=$?
        if [ ${exit_code:-0} -ne 0 ]; then
          echo "❌ Tests failed with exit code: $exit_code"
          echo "::error title=Test Failure::One or more tests failed. Check the test output above for details."
          exit $exit_code
        else
          echo "✅ All tests passed successfully!"
        fi
      
    - name: Upload test results and coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-and-coverage
        path: |
          cannasoltech_automation/coverage/
        retention-days: 30
        
    - name: Comment test results on PR
      uses: actions/github-script@v7
      if: always() && github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const { context } = github;
          
          // Determine if tests passed or failed based on previous step
          const testsPassed = ${{ job.status == 'success' }};
          const statusEmoji = testsPassed ? '✅' : '❌';
          const statusText = testsPassed ? 'PASSED' : 'FAILED';
          
          const comment = `## ${statusEmoji} Flutter CI Tests ${statusText}
          
          **Workflow:** [${context.workflow}](${context.payload.repository.html_url}/actions/runs/${context.runId})
          **Commit:** ${context.sha.substring(0, 7)}
          
          ${testsPassed ? 
            '🎉 All tests are passing! Your changes look good.' : 
            '⚠️ Some tests are failing. Please check the workflow logs for details.'}
          
          ---
          *This comment was automatically generated by the CI pipeline.*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });